### ISSUE TITLE
Conversion to Node.js

### ISSUE THREAD

**Issue by blacksmithgu** [anst/groupdesk#6]
Now that we actually have time for it, we can probably go ahead and convert the project (and expand upon it) by converting to Node.js with a MongoDB backend. Discuss here.

**Comment by anst** [comment]
https://www.npmjs.org/package/mustache-express

I would prefer this for frontend work.

**Comment by blacksmithgu** [comment]
I personally think this would work even better:
https://github.com/wycats/handlebars.js

There's an express-port which I need to find.

**Comment by anst** [comment]
https://www.npmjs.org/package/express3-handlebars

Yeah handlebars is much better because templates.

**Comment by chufanl** [comment]
We should use git submodules for dependencies so that our code isn't filled with random stuff from libraries

**Comment by anst** [comment]
NPM will just manage libraries for us. All we have to do is .gitignore the node_modules directory.

**Comment by chufanl** [comment]
I meant libraries that are not node based.

Edit: To clarify, I was referring to JS and CSS dependencies that were part of the views; previously we ended up adding over 8000 lines of library code to our repo.
